name: Github action playground

on: workflow_dispatch

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      BOBO: "visible env var"
      BABA: ${{ secrets.PRECIOUS }}
    steps:
      - name: Run env command
        run: echo $BOBO
      - name: Run env command
        run: echo $BABA
